# fly.toml app configuration file generated for dot-trade-in on 2024-12-06T10:52:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dot-trade-in'
primary_region = 'otp'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_API_KEY = '5c0bcd7a4d25effc7cc9958fa442ee99'
  SHOPIFY_APP_URL = 'https://dot-trade-in.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
